"""Add departure and arrival times to Bus

Revision ID: 0ccbbc2518be
Revises: d0c41ed0cf0c
Create Date: 2025-04-15 06:36:39.597241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ccbbc2518be'
down_revision = 'd0c41ed0cf0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bus', schema=None) as batch_op:
        batch_op.add_column(sa.Column('capacity', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('model', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('year', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('route_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'route', ['route_id'], ['id'])
        batch_op.drop_column('route')
        batch_op.drop_column('destination')
        batch_op.drop_column('source')
        batch_op.drop_column('arrival_time')
        batch_op.drop_column('departure_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bus', schema=None) as batch_op:
        batch_op.add_column(sa.Column('departure_time', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('arrival_time', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('source', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('destination', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('route', sa.VARCHAR(length=100), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('route_id')
        batch_op.drop_column('year')
        batch_op.drop_column('model')
        batch_op.drop_column('capacity')

    # ### end Alembic commands ###
