"""Added phone column to User model

Revision ID: a371875a3cad
Revises: 0e64eaaf0fd8
Create Date: 2025-04-14 10:52:16.594082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a371875a3cad'
down_revision = '0e64eaaf0fd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bookings')
    op.drop_table('users')
    op.drop_table('buses')
    op.drop_table('booking')
    op.drop_table('schedules')
    op.drop_table('routes')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.LargeBinary(length=200),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.LargeBinary(length=200),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
        batch_op.drop_column('phone')

    op.create_table('routes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('route_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('origin', sa.VARCHAR(length=100), nullable=False),
    sa.Column('destination', sa.VARCHAR(length=100), nullable=False),
    sa.Column('distance', sa.FLOAT(), nullable=True),
    sa.Column('estimated_duration', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedules',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('bus_id', sa.INTEGER(), nullable=False),
    sa.Column('departure_time', sa.TIME(), nullable=False),
    sa.Column('arrival_time', sa.TIME(), nullable=False),
    sa.Column('day_of_week', sa.VARCHAR(length=10), nullable=False),
    sa.ForeignKeyConstraint(['bus_id'], ['buses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('booking',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('bus_id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.VARCHAR(length=50), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('buses',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('bus_number', sa.VARCHAR(length=50), nullable=False),
    sa.Column('capacity', sa.INTEGER(), nullable=False),
    sa.Column('model', sa.VARCHAR(length=50), nullable=True),
    sa.Column('year', sa.INTEGER(), nullable=True),
    sa.Column('route_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bus_number'),
    sa.UniqueConstraint('route_id')
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), nullable=False),
    sa.Column('password', sa.VARCHAR(length=200), nullable=False),
    sa.Column('role', sa.VARCHAR(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('bookings',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('schedule_id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('seats_booked', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
